### ISSUE TITLE
parent pom and module pom breakages

### ISSUE THREAD

**Issue by yaweiw** [yaweiw/azure-spring-cloud-playground#24]
parent pom:
should be <packaging>pom</packaging> not <packaging>jar</packaging>

module pom:
should be <relativePath>../pom.xml</relativePath> not <relativePath/>

**Comment by yaweiw** [comment]
@warrenzhu25 @sophiaso @Incarnation-p-lee

**Comment by Incarnation-p-lee** [comment]
I will prepare PR for this.

**Comment by warrenzhu25** [comment]
Fixed.
