### ISSUE TITLE
add a home page in gateway where all services endpoints are shown

### ISSUE THREAD

**Issue by yaweiw** [yaweiw/azure-spring-cloud-playground#33]
docker compose up should be able to output the endpoint of gateway server and there should be a home page rendered where all services endpoints are shown.

**Comment by yaweiw** [comment]
@sophiaso @Incarnation-p-lee

**Comment by yaweiw** [comment]
who is picking this up? @sophiaso  @Incarnation-p-lee

**Comment by sophiaso** [comment]
#55
