### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by yaweiw** [yaweiw/azure-spring-cloud-playground#76]
When click Login, was given this error:
Nonce received: 387be11b-7129-4895-a075-35aabc4fcb32 is not same as requested: c83def34-830c-4d04-82e0-5aa5d08ba539387be11b-7129-4895-a075-35aabc4fcb32||

**Comment by yaweiw** [comment]
@sophiaso

**Comment by sophiaso** [comment]
Cannot reproduce currently and will keep an eye on this.

Seems a similar issue but was old in 2014. https://github.com/Azure-Samples/active-directory-dotnet-webapp-openidconnect/wiki/The-'nonce'-found-in-the-jwt-token-did-not-match-the-expected-nonce

May not be related.
